[project]
name = "my-new-pro"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.payment]
path = "contracts/payment.clar"
depends_on = []

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }