[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "swear vintage nominee hub husband song family beef labor trick exile fitness spin idle comfort crater news penalty hole extra prepare crystal venture front"

